---
 - name: "Configure user configuration data to persistent drive"
   become: yes
   lineinfile: 
     path: "/etc/profile"
     line: export XDG_CONFIG_HOME={{ persistent_data_drive_mount_path }}
 - name: Create download directory
   file:
     path: "{{ persistent_data_drive_mount_path }}/Downloads"
     state: directory
 - name: "Create download folder"
   command: "gsettings set org.blueman.transfer shared-path '{{ persistent_data_drive_mount_path }}/Downloads'"
