---
- name: Download terraform installation
  get_url: 
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform_{{ terraform_version }}"

- name: make sure unzip is installed for extracting terraform
  become: yes
  apt:
    name: unzip
    state: present
    force_apt_get: True    
- name: Install terraform
  unarchive:
    src: "/tmp/terraform_{{ terraform_version }}"
    dest: /usr/local/bin
    remote_src: yes