---
- name: Install docker
  become: yes
  apt:
    name: docker.io
    state: present
    force_apt_get: True    
- name: Start docker service
  become: yes
  command: systemctl start docker
- name: Enable docker service
  become: yes
  command: systemctl enable docker