---
- name: Install aws
  become: yes
  apt:
    name: awscli
    state: present
    force_apt_get: True    
- name: Install sam
  become: yes
  command: python3 -m pip install aws-sam-cli
- name: Check stats on aws config and credentials on persistent drive
  stat: 
    path: "{{ persistent_data_drive_mount_path }}/.aws"
  register: aws_credentials_path
- name: If present on persistent drive, copy aws config and credentials to home directory
  become: yes
  copy: 
    src: "{{ persistent_data_drive_mount_path }}/.aws" 
    dest: "/home/{{ vm_user_name}}"
  when: aws_credentials_path.stat.exists and aws_credentials_path.stat.isdir 